apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mycluster
  region: ap-south-1

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 2 
    ssh: 
      publicKeyName:  firstos_key-1
  - name: ng-2
    instanceType: t3.small
    desiredCapacity: 1
    ssh: 
      publicKeyName:  firstos_key-1

